FROM python:3.10-alpine

WORKDIR /api

COPY poetry.lock pyproject.toml /api/

RUN pip install poetry --no-cache-dir && \
    poetry config virtualenvs.create false \
    && poetry install --no-root

COPY . /api

EXPOSE 8000
CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
