FROM python:3.12

COPY . /api
WORKDIR /api

RUN pip install poetry
RUN poetry config virtualenvs.create false \
    && poetry install

CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
EXPOSE 8000
