version: '3.9'

services:
  meal-muse-api:
    container_name: meal-muse-api
    build:
      dockerfile: dockerfile.local
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./api:/api/api/
      - ./core:/api/core/
      - ./factories:/api/factories/
      - ./adapters:/api/adapters/
    env_file:
      - .env
    depends_on:
      - meal-muse-db
    networks:
      - meal-muse-network

  meal-muse-db:
    container_name: meal-muse-db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mealmuse_db
    env_file:
      - .env
    networks:
      - meal-muse-network

networks:
  meal-muse-network:


volumes:
  postgres-data:


