"""initial-status

Revision ID: ff15a31edd60
Revises: c5cfd4256a7d
Create Date: 2024-08-29 22:27:25.788689

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'ff15a31edd60'
down_revision: Union[str, None] = 'c5cfd4256a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
