name:  Meal Muse Backend CI

on: 
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Python 3.11
              uses: actions/setup-python@v4
              with:
                  python-version: '3.11'
            
            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                virtualenvs-create: true
                virtualenvs-in-project: true

            - name: Install dependencies
              run: |
                  make install

            - name: Run linters
              run: |
                  source .venv/bin/activate && make lint

            - name: Run tests
              run: |
                    source .venv/bin/activate && make test
            
